# https://www.linkedin.com/learning/using-rust-with-python/basic-rust-library
# Basic Rust library (2:33) : makefile
build:
	cargo build --release
	#cp target/release/py03-example.so .
	#^=> cp: target/release/py03-example.so: No such file or directory

clean:
	# Remove the build .so file
	rm -f py03-example.so
	
# run like this:
# make clean
# make build
