build:
	cargo build --release

lint:
	# To look for build warnings
	cargo clippy

fmt:
	# Remove superfluous empty lines
	cargo format

run:
	# make run === cargo run
	cargo run
	
runInput:
	# to call with a passed in value for input:
	cargo run -- --input "macro"
	
runHelp:
	# to show a help screen
	cargo run -- --help

test:
	cargo test
	
# run like this:
# make lint
# make build
# make fmt
