build:
	cargo build --release

lint:
	# To look for build warnings
	cargo clippy

fmt:
	# Remove superfluous empty lines
	cargo format

run:
	# make run === cargo run
	cargo run
	
# run like this:
# make lint
# make build
# make fmt
